#!/usr/bin/env python3
"""
Initialize a new project folder to use the Writing Mentor Framework.

This script sets up a class folder with:
- wmf-config.yaml pointing to the central framework
- Minimal CLAUDE.md with review instructions
- Template assignment.md and rubric.md
- Empty submissions/ folder

Usage:
    python init_project.py --target /path/to/class/folder [--framework /path/to/framework]

If --framework is not specified, uses the parent directory of this script.
"""

import argparse
import sys
from pathlib import Path


def get_framework_path(script_path: Path) -> Path:
    """Get the framework root path from script location."""
    # Script is in framework/scripts/, so parent.parent is framework root
    return script_path.parent.parent


def create_config(target: Path, framework: Path) -> None:
    """Create wmf-config.yaml in the target folder."""
    config_content = f'''# Writing Mentor Framework - Configuration
# Generated by init_project.py

# Path to the framework installation
framework_path: {framework}

# Assignment-specific files (in this folder)
assignment: assignment.md
rubric: rubric.md

# Optional: Course-specific concepts for assumption validation
# Create this file or set to null to use general principles
course_concepts: course_concepts.md

# Submission handling
submissions:
  folder: submissions
  rounds:
    enabled: false

# Output folders (created automatically during review)
output:
  extracted: grading_extracted
  rendered: grading_rendered
  feedback: grading_feedback

# Optional: Turnitin reports
turnitin: turnitin

# Review settings
review:
  sequential: true
  compare_to_round: null
'''
    (target / 'wmf-config.yaml').write_text(config_content)
    print(f"  Created: wmf-config.yaml")


def create_claude_md(target: Path, framework: Path) -> None:
    """Create minimal CLAUDE.md in the target folder."""
    claude_content = f'''# CLAUDE.md

This folder uses the **Writing Mentor Framework** for reviewing submissions.

## Configuration

Framework location: `{framework}`
Settings: See `wmf-config.yaml`

## Quick Start

1. Place submissions in `submissions/`
2. Ask Claude to review the submissions

## Commands

**Check dependencies:**
```bash
python {framework}/skills/grading/scripts/check_dependencies.py
```

**Extract text from submissions:**
```bash
python {framework}/skills/grading/scripts/extract_submission_text.py --input submissions --out grading_extracted
```

**Render Excel charts:**
```bash
python {framework}/skills/grading/scripts/render_xlsx_quicklook.py --input submissions --out grading_rendered
```

## Review Workflow

When reviewing submissions, Claude Code should:

1. **Read `wmf-config.yaml`** to get framework path and settings
2. **Read framework instructions** from `{framework}/skills/grading/SKILL.md`
3. **Read assignment requirements** from `assignment.md`
4. **Read evaluation criteria** from `rubric.md`
5. **Read writing principles** from `{framework}/skills/grading/references/economical_writing_principles.md`
6. **Read course concepts** from `course_concepts.md` (if present) for assumption validation
7. **Follow the isolated review workflow** in the framework SKILL.md

## Key Principles

- **Two-tier feedback**: Reviewer Notes (for instructor) + Writer Feedback (for student)
- **Data validation**: Check internal consistency, verify formulas match charts
- **Assumption auditing**: Check against economic/statistical principles
- **Isolated review**: Each submission reviewed by fresh agent (no cross-contamination)
- **Teaching focus**: Guide writers to discover fixes themselves

## For Multi-Round Reviews

1. Enable rounds in `wmf-config.yaml`
2. Use subfolders: `submissions/round1/`, `submissions/round2/`
3. Set `compare_to_round` in config for resubmission comparisons

See framework README for detailed instructions.
'''
    (target / 'CLAUDE.md').write_text(claude_content)
    print(f"  Created: CLAUDE.md")


def create_template_files(target: Path) -> None:
    """Create template assignment.md and rubric.md."""

    assignment_content = '''# Assignment Requirements

<!-- Replace this with your assignment requirements -->

## Overview

[Describe the assignment purpose and context]

## Required Components

1. [Component 1]
2. [Component 2]
3. [Component 3]

## Formatting Requirements

- [Length, format, citation style, etc.]

## Due Date

[Date]

## Resources Provided

- [Any data files, readings, etc.]
'''

    rubric_content = '''# Evaluation Rubric

<!-- Replace this with your evaluation criteria -->

## Total Points: [X]

### [Criterion 1] ([X] points)

| Score | Description |
|-------|-------------|
| Excellent (X) | [What excellent work looks like] |
| Competent (X) | [What competent work looks like] |
| Developing (X) | [What developing work looks like] |
| Insufficient (X) | [What insufficient work looks like] |

### [Criterion 2] ([X] points)

| Score | Description |
|-------|-------------|
| Excellent (X) | [Description] |
| Competent (X) | [Description] |
| Developing (X) | [Description] |
| Insufficient (X) | [Description] |

<!-- Add more criteria as needed -->
'''

    course_concepts_content = '''# Course Concepts

<!-- Optional: Add domain-specific concepts for enhanced assumption validation -->
<!-- Without this file, the framework still provides full feedback on writing quality, -->
<!-- analysis structure, and data validation - it just won't catch course-specific errors -->

## Key Principles

- [Principle 1]
- [Principle 2]

## Common Errors to Flag

- [Error type 1: description and correct approach]
- [Error type 2: description and correct approach]

## Terminology

- **Term 1**: Definition
- **Term 2**: Definition

## Example: Economics Course

```
## GDP Comparisons
- Cross-time comparisons require real (inflation-adjusted) GDP, not nominal
- Cross-country comparisons require PPP adjustment
- Per-capita normalization needed for different population sizes

## Statistical Claims
- Correlation does not imply causation
- Statistical significance requires appropriate tests
```
'''

    (target / 'assignment.md').write_text(assignment_content)
    print(f"  Created: assignment.md (template)")

    (target / 'rubric.md').write_text(rubric_content)
    print(f"  Created: rubric.md (template)")

    (target / 'course_concepts.md').write_text(course_concepts_content)
    print(f"  Created: course_concepts.md (template)")


def create_folders(target: Path) -> None:
    """Create necessary folders."""
    folders = ['submissions', 'turnitin']
    for folder in folders:
        (target / folder).mkdir(exist_ok=True)
        # Add .gitkeep to empty folders
        gitkeep = target / folder / '.gitkeep'
        if not gitkeep.exists():
            gitkeep.touch()
    print(f"  Created: submissions/, turnitin/")


def main():
    parser = argparse.ArgumentParser(
        description='Initialize a new project folder for the Writing Mentor Framework'
    )
    parser.add_argument(
        '--target', '-t',
        required=True,
        help='Target folder to initialize (will be created if it does not exist)'
    )
    parser.add_argument(
        '--framework', '-f',
        help='Path to the framework installation (default: parent of this script)'
    )
    parser.add_argument(
        '--force',
        action='store_true',
        help='Overwrite existing files'
    )
    args = parser.parse_args()

    target = Path(args.target).expanduser().resolve()
    script_path = Path(__file__).resolve()

    if args.framework:
        framework = Path(args.framework).expanduser().resolve()
    else:
        framework = get_framework_path(script_path)

    # Validate framework path
    skill_file = framework / 'skills' / 'grading' / 'SKILL.md'
    if not skill_file.exists():
        print(f"Error: Framework not found at {framework}")
        print(f"  Expected to find: {skill_file}")
        sys.exit(1)

    # Create target folder if needed
    target.mkdir(parents=True, exist_ok=True)

    # Check for existing files
    existing_files = []
    for f in ['wmf-config.yaml', 'CLAUDE.md', 'assignment.md', 'rubric.md']:
        if (target / f).exists():
            existing_files.append(f)

    if existing_files and not args.force:
        print(f"Error: Target folder already contains: {', '.join(existing_files)}")
        print("  Use --force to overwrite existing files")
        sys.exit(1)

    print(f"\nInitializing Writing Mentor Framework project:")
    print(f"  Target: {target}")
    print(f"  Framework: {framework}")
    print()

    create_config(target, framework)
    create_claude_md(target, framework)
    create_template_files(target)
    create_folders(target)

    print()
    print("Project initialized successfully!")
    print()
    print("Next steps:")
    print("  1. Edit assignment.md with your assignment requirements")
    print("  2. Edit rubric.md with your evaluation criteria")
    print("  3. (Optional) Edit course_concepts.md with domain-specific principles")
    print("  4. Place submissions in the submissions/ folder")
    print("  5. Open Claude Code and ask to review the submissions")


if __name__ == '__main__':
    main()
